// Code generated by "stringer -type=ID -trimprefix=ID"; DO NOT EDIT.

package erb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IDVER-1]
	_ = x[IDPOS-2]
	_ = x[IDSTAT-3]
	_ = x[IDDOPS-4]
	_ = x[IDVEL-5]
	_ = x[IDSVI-6]
}

const _ID_name = "VERPOSSTATDOPSVELSVI"

var _ID_index = [...]uint8{0, 3, 6, 10, 14, 17, 20}

func (i ID) String() string {
	i -= 1
	if i >= ID(len(_ID_index)-1) {
		return "ID(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ID_name[_ID_index[i]:_ID_index[i+1]]
}
