// Code generated by "stringer -type SVType -trimprefix SVType"; DO NOT EDIT.

package erb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SVTypeGPS-0]
	_ = x[SVTypeGLONASS-1]
	_ = x[SVTypeGalileo-2]
	_ = x[SVTypeQZSS-3]
	_ = x[SVTypeBeiDou-4]
	_ = x[SVTypeLEO-5]
	_ = x[SVTypeSBAS-6]
}

const _SVType_name = "GPSGLONASSGalileoQZSSBeiDouLEOSBAS"

var _SVType_index = [...]uint8{0, 3, 10, 17, 21, 27, 30, 34}

func (i SVType) String() string {
	if i >= SVType(len(_SVType_index)-1) {
		return "SVType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SVType_name[_SVType_index[i]:_SVType_index[i+1]]
}
