// Code generated by "stringer -type FixType -trimprefix FixType"; DO NOT EDIT.

package erb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FixTypeNoFix-0]
	_ = x[FixTypeSingle-1]
	_ = x[FixTypeFloat-2]
	_ = x[FixTypeRTK-3]
}

const _FixType_name = "NoFixSingleFloatRTK"

var _FixType_index = [...]uint8{0, 5, 11, 16, 19}

func (i FixType) String() string {
	if i >= FixType(len(_FixType_index)-1) {
		return "FixType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FixType_name[_FixType_index[i]:_FixType_index[i+1]]
}
